env:
    MANIFEST: https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs
    DEVICE: a73xq
    OEM: samsung
    COMMON: sm7325-common
    DT_LINK: https://github.com/ITTECH-ROM/android_device_samsung_a73xq.git -b lineage-20
    DT_PATH: device/$OEM/$DEVICE
    DTCM_LINK: https://github.com/ITTECH-ROM/android_device_samsung_sm7325-common.git -b lineage-20
    DTCM_PATH: device/$OEM/$COMMON
    VT_LINK: https://github.com/ROM-CUSTOM-SAMSUNG/android_vendor_samsung_a73xq.git -b lineage-20
    VT_PATH: vendor/$OEM/$DEVICE
    VTCM_LINK: https://github.com/ROM-CUSTOM-SAMSUNG/android_vendor_samsung_sm7325-common.git -b lineage-20
    VTCM_PATH: vendor/$OEM/$COMMON
    KT_LINK: https://gitlab.com/nguyenhung9xdev2022/android_kernel_samsung_sm7325.git -b lineage-20
    PLATFORM: sm7325
    KT_PATH: kernel/$OEM/$PLATFORM
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: lineage*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ghcr.io/nguyenhung9xdev2024/docker:arch
      cpu: 4
      memory: 16G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/lineage
      - cd ~/lineage
      - repo init --depth=1 -u $MANIFEST
      - repo sync -j8 --force-sync --no-tags --no-clone-bundle
      - git clone $DT_LINK $DT_PATH
      - git clone $DTCM_LINK $DTCM_PATH
      - git clone $VT_LINK $VT_PATH
      - git clone $VTCM_LINK $VTCM_PATH
      - git clone $KT_LINK $KT_PATH
      - rm -rf hardware/samsung
      - git clone https://github.com/LineageOS/android_hardware_samsung.git -b lineage-20 hardware/samsung
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch "$LUNCH_COMBO"
      - mka -j31
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
