env:
    OEM: samsung
    CODENAME: a73xq
    PLATFORM: sm7325
    COMMON: sm7325-common
    CIRRUS_CI: true
    CIRRUS_SHELL: bash
    TARGET: m bacon -j16
    ROM_NAME: PixysOS
    PRODUCT_NAME: pixys_a73xq
    VARIANT: userdebug
    ROM_REPO: "https://github.com/PixysOS/manifest.git"
    ROM_BRANCH: thirteen
    DEVICE_REPO: "https://github.com/ROM-CUSTOM-SAMSUNG/android_device_samsung_a73xq.git"
    DEVICE_BRANCH: thirteen
    DEVICE_COMMON_REPO: "https://github.com/ROM-CUSTOM-SAMSUNG/android_device_samsung_sm7325-common.git"
    DEVICE_COMMON_BRANCH: thirteen
    VENDOR_REPO: "https://github.com/ROM-CUSTOM-SAMSUNG/android_vendor_samsung_a73xq.git"
    VENDOR_BRANCH: thirteen
    VENDOR_COMMON_REPO: "https://github.com/ROM-CUSTOM-SAMSUNG/android_vendor_samsung_sm7325-common.git"
    VENDOR_COMMON_BRANCH: thirteen
    KERNEL_REPO: "https://gitlab.com/nguyenhung9xdev2022/android_kernel_samsung_sm7325.git"
    KERNEL_BRANCH: thirteen
    USERNAME: nguyenhung9xdev2024
    USERMAIL: nguyenhung9xdev2024
    OUTPUT: PixysOS*.zip

task:
  name: "ROM Build"
  timeout_in: 240m
  trigger_type: manual
  container:
      image: ghcr.io/nguyenhung9xdev2024/docker:arch
      cpu: 8
      memory: 32G

# CLONE_SCRIPT_script: |
 #   if [ -z "$CIRRUS_PR" ]; then
 #     git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  #    git reset --hard $CIRRUS_CHANGE_IN_REPO
  #  else
  #    git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  #    git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
   #   git reset --hard $CIRRUS_CHANGE_IN_REPO
  #  fi    

  SYNC_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/nguyenhung9xdev2024/rom-builder-ci/main/build.sh | bash

  BUILD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/nguyenhung9xdev2024/rom-builder-ci/main/sync_rom.sh | bash

  UPLOAD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/nguyenhung9xdev2024/rom-builder-ci/main/upload_rom.sh | bash
